// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20200518155449_Countries")]
    partial class Countries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 7,
                            Name = "France"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ukraine"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "test1@users.com",
                            Password = "978egret4cJPDGQ5B/UIAPTfNob4DxDsEBZmHyxK0m705w7gZsLLM1Stle18VhwT"
                        },
                        new
                        {
                            Id = -2,
                            Email = "test2@users.com",
                            Password = "lThbqsIUV2GzTsa4g716ocuBSsaYu0QW1PIcziBBxVX4fgYjcFjokedNOzJ9KmkR"
                        },
                        new
                        {
                            Id = -3,
                            Email = "test3@users.com",
                            Password = "qujrA66Os5vU/VS1OhBSv0xTkzZZzyrlPfjNp+tDZp3NYWrn52n+WJ7I6awKY9v/"
                        },
                        new
                        {
                            Id = -4,
                            Email = "test4@users.com",
                            Password = "rxQLuMKgW7rksxOkAY0t5NNFhduDuuuPmBI9W8LXky5STiZakwy49yafh9alWRfx"
                        },
                        new
                        {
                            Id = -5,
                            Email = "test5@users.com",
                            Password = "LshVk5JSb49kQ7N+VOvXu680zCYlgmi7xvVqyekJ9Qn8Jk5AbR9unQ+DBLi5MJRA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
