// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20200518230653_UserSettingsMockData")]
    partial class UserSettingsMockData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Country = 2,
                            Email = "test1@users.com",
                            FirstName = "Fn1",
                            Gender = 0,
                            Language = 3,
                            LastName = "Ln1",
                            Password = "y69sD36qZyBUUSRiI7l8rlk038JRgWao2P60v106CgGBEYCHslsmjo4a4PzIY+Cg"
                        },
                        new
                        {
                            Id = -2,
                            Country = 0,
                            Email = "test2@users.com",
                            FirstName = "FirstName2",
                            Gender = 1,
                            Language = 0,
                            LastName = "LastName2",
                            Password = "APQonDLtkfTx8LjAq/h3EKjIofprGeOeqIqbzbj7+l6nwlbrPPsPYLxTg3W1is+e"
                        },
                        new
                        {
                            Id = -3,
                            Country = 1,
                            Email = "test3@users.com",
                            FirstName = "FFFF3",
                            Gender = 2,
                            Language = 1,
                            LastName = "LLLL3",
                            Password = "brLwfLObHtt4nSPbYV9F9ny8SAp9EQmzmqo0SrQA1n45OwTtGyb+JEC+7Du28/2P"
                        },
                        new
                        {
                            Id = -4,
                            Country = 1,
                            Email = "test4@users.com",
                            FirstName = "LongFirstName4",
                            Gender = 1,
                            Language = 0,
                            LastName = "LongLastName4",
                            Password = "ntkVOkoRXx9HsA11wPqw6JjYSQ/1K02psibRR3+lTZaL1mWgB2bFqbi93p6IlJej"
                        },
                        new
                        {
                            Id = -5,
                            Country = 3,
                            Email = "test5@users.com",
                            FirstName = "First5",
                            Gender = 0,
                            Language = 2,
                            LastName = "Last5",
                            Password = "3ILzrBfqh9jiW/MXzCnrcJb6su2fKHK3YKJrDh8gJe3YBzzoRDg6z5Cd4ArueM5f"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
