// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "test1@users.com",
                            Password = "d53tbpepSAOL9x9Xo2ea/LLhaJSgmyO0CCXFrYcdk66s3icf5o3lPGejbtagCjdD"
                        },
                        new
                        {
                            Id = -2,
                            Email = "test2@users.com",
                            Password = "8IfxrRQwpbu+tUzLRNo3uXnyiNrDuJRcG1tLJimSeCnF2RqdGUO6w62PJJFD+IEV"
                        },
                        new
                        {
                            Id = -3,
                            Email = "test3@users.com",
                            Password = "skmRAX40jXIsx0doAOE1eDH9C48ZKbgBi9pAn0f1jUnJl7iJ91TI4/o1S+8hJxwF"
                        },
                        new
                        {
                            Id = -4,
                            Email = "test4@users.com",
                            Password = "AkcieaUZvile78XDpN8+XD3JKsmKKmrwuWPuRl5SEBJqqkwu/ZISVgxJZgRRH5RE"
                        },
                        new
                        {
                            Id = -5,
                            Email = "test5@users.com",
                            Password = "6f2BX2AFu7Me7zg5PLfPj/zZxndZYi05+btyZ1DPYiJcfvwYn+j4+LB29rqb4IYS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
