// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Country = 3,
                            Email = "test1@users.com",
                            FirstName = "Fn1",
                            Gender = 0,
                            Language = 3,
                            LastName = "Ln1",
                            Password = "83x1MpGkCOw7x3Jzb9CVHcI6VbyxeZ99bXOZys2XLD0YfQTnUBuzQyf/Vj6shZFx"
                        },
                        new
                        {
                            Id = -2,
                            Country = 1,
                            Email = "test2@users.com",
                            FirstName = "FirstName2",
                            Gender = 2,
                            Language = 0,
                            LastName = "LastName2",
                            Password = "QV0YR2Pv6MtOVTS/sSLN+v2zPOl0gyAZUxG6Btu/i7Xz9hMecMGFujOrBg5ZUGlX"
                        },
                        new
                        {
                            Id = -3,
                            Country = 2,
                            Email = "test3@users.com",
                            FirstName = "FFFF3",
                            Gender = 3,
                            Language = 1,
                            LastName = "LLLL3",
                            Password = "6lLrFyf6gplT1VJH/tXjc6EkYqwbyBQMaRppE6IaF7xWJd3ekNnMIoYHmuHY/l2D"
                        },
                        new
                        {
                            Id = -4,
                            Country = 2,
                            Email = "test4@users.com",
                            FirstName = "LongFirstName4",
                            Gender = 2,
                            Language = 0,
                            LastName = "LongLastName4",
                            Password = "eePej1CqKBZ6Id36WWmiPP9eF30dPvBu6BvQJdha08e0WH3/24mqFvFNHTPYpam1"
                        },
                        new
                        {
                            Id = -5,
                            Country = 0,
                            Email = "test5@users.com",
                            Gender = 0,
                            Language = 2,
                            LastName = "Last5",
                            Password = "l/Xw4PpHfKbLQZDCG9cjzPkVqxb1SFSCKy/Dgq8kAWhDJXcEHVvJaDnQoPY6PiDZ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
