const SERVER_AVATARS_PATH = 'assets/avatars',
      MAX_AVATAR_SIZE_MB = 2,
      MAX_WAYPOINT_SIZE_MB = 5,
      MAX_WAYPOINT_FILE_COUNT = 5,
      SERVER_SCHEDULED_PLACE_TO_EAT_PATH = 'scheduledPlaceToEat',
      MAX_FILE_SIZE_SCHEDULET_PLACE_TO_EAT = 1024 * 1024 * 10;

export {
  SERVER_AVATARS_PATH,
  MAX_AVATAR_SIZE_MB,
  MAX_WAYPOINT_SIZE_MB,
  MAX_WAYPOINT_FILE_COUNT,
  SERVER_SCHEDULED_PLACE_TO_EAT_PATH,
  MAX_FILE_SIZE_SCHEDULET_PLACE_TO_EAT
};
