const SERVER_AVATARS_PATH = 'assets/avatars',
      MAX_AVATAR_SIZE_MB = 2,
      SERVER_ENTERTAINMENT_PATH = 'entertainment',
      MAX_ENTERTAINMENT_SIZE_MB = 2,
      MAX_WAYPOINT_SIZE_MB = 5,
      MAX_WAYPOINT_FILE_COUNT = 5,
      SERVER_SCHEDULED_PLACE_TO_EAT_PATH = 'scheduledPlaceToEat',
      MAX_FILE_SIZE_SCHEDULET_PLACE_TO_EAT = 1024 * 1024 * 10,
      MAX_FILE_COUNT_SCHEDULET_PLACE_TO_EAT = 10,
      SERVER_ACCOMODATIONS_PATH = 'accommodations',
      MAX_ACCOMODATION_SIZE_MB = 2;

export {
  SERVER_AVATARS_PATH,
  MAX_AVATAR_SIZE_MB,
  MAX_WAYPOINT_SIZE_MB,
  MAX_WAYPOINT_FILE_COUNT,
  SERVER_SCHEDULED_PLACE_TO_EAT_PATH,
  MAX_FILE_SIZE_SCHEDULET_PLACE_TO_EAT,
  MAX_FILE_COUNT_SCHEDULET_PLACE_TO_EAT,
  SERVER_ENTERTAINMENT_PATH,
  MAX_ENTERTAINMENT_SIZE_MB,
  SERVER_ACCOMODATIONS_PATH,
  MAX_ACCOMODATION_SIZE_MB
};
