export {
  SERVER_AVATARS_PATH,
  MAX_AVATAR_SIZE_MB,
  SERVER_SCHEDULED_PLACE_TO_EAT_PATH,
  MAX_FILE_SIZE_SCHEDULET_PLACE_TO_EAT,
  MAX_WAYPOINT_SIZE_MB,
  MAX_WAYPOINT_FILE_COUNT
} from './fileSettings.js';
export { mapSettings, LINE_PATH_CONFIG, POINT_MARKER_ICON_CONFIG } from './mapSettings.js';
export { EMAIL_REGEX, LINK_REGEX } from './validation.js';
