export {
  SERVER_AVATARS_PATH,
  MAX_AVATAR_SIZE_MB,
  SERVER_ENTERTAINMENT_PATH,
  MAX_ENTERTAINMENT_SIZE_MB,
  MAX_WAYPOINT_SIZE_MB,
  MAX_WAYPOINT_FILE_COUNT,
  SERVER_ACCOMODATIONS_PATH,
  MAX_ACCOMODATION_SIZE_MB
} from './fileSettings.js';

export { mapSettings, LINE_PATH_CONFIG, POINT_MARKER_ICON_CONFIG } from './mapSettings.js';
export {
  EMAIL_REGEX,
  URL_REGEX
} from './validation.js';

export { PAGINTAION_ACCOMMODATION_PAGE_SIZE } from './paginationSettings.js';
