export {
  SERVER_AVATARS_PATH,
  MAX_AVATAR_SIZE_MB,
  SERVER_ENTERTAINMENT_PATH,
  MAX_ENTERTAINMENT_SIZE_MB,
  MAX_WAYPOINT_SIZE_MB,
  MAX_WAYPOINT_FILE_COUNT,
  SERVER_ACCOMODATIONS_PATH,
  SERVER_SCHEDULED_PLACE_TO_EAT_PATH,
  MAX_FILE_SIZE_SCHEDULET_PLACE_TO_EAT,
  MAX_FILE_COUNT_SCHEDULET_PLACE_TO_EAT,
  MAX_ACCOMODATION_SIZE_MB
} from './fileSettings.js';

export { mapSettings, LINE_PATH_CONFIG, POINT_MARKER_ICON_CONFIG } from './mapSettings.js';
export { PAGINTAION_ACCOMMODATION_PAGE_SIZE } from './paginationSettings.js';
export { EMAIL_REGEX, LINK_REGEX } from './validation.js';
export { PAGINTAION_SHEDULED_PLACE_TO_EAT_PAGE_SIZE } from './paginationSettings.js';
